# -*- coding: utf-8 -*-
"""
I use .count to calculate the number of each alphbet from A to Z, then sum up (the number)*(the number -1)
as the IC formula, dividing it by (the total number of the alphabet)*(total number of alphabet-1)
"""

sentence="RHVST TEYSJ KMHUM BBCLC GLKBM HBSJH HDAYC PPWHD UUTAP STJAI YMXKA OKARN NATNG CVRCH BNGJU EMXWH UERZE RLDMX MASRT LAHRJ KIILJ BQCTI BVFZW TKBQE OPKEQ OEBMU NUTAK ZOSLD MKXVO YELLX SGHTT PNROY MORRW BWZKX FFIQJ HVDZZ JGJZY IGYAT KWVIB VDBRM BNVFC MAXAM CALZE AYAZK HAOAA ETSGZ AAJFX HUEKZ IAKPM FWXTO EBUGN THMYH FCEKY VRGZA QWAXB RSMSI IWHQM HXRNR XMOEU ALYHN ACLHF AYDPP JBAHV MXPNF LNWQB WUGOU LGFMO BJGJB PEYVR GZAQW ANZCL XZSVF BISMB KUOTZ TUWUO WHFIC EBAHR JPCWG CVVEO LSSGN EFGCC SWHYK BJHMF ONHUE BYDRS NVFMR JRCHB NGJUB TYRUU TYVRG ZAXWX CSADX YIAKL INGXF FEEST UWIAJ EESFT HAHRT WZGTM CRS"

list=["CRYPTANALYSIS IN RECENT PUBLICATIONS ALSO CRYPTANALYSIS\
REFERS IN THE ORIGINAL SENSE TO THE STUDY OF METHODS AND\
TECHNIQUES TO OBTAIN INFORMATION FROM SEALED TEXTS THIS\
INFORMATION CAN BE BOTH THE KEY USED AND THE ORIGINAL TEXT\
NOWADAYS, THE TERM CRYPTANALYSIS MORE GENERALLY REFERS TO\
THE ANALYSIS OF CRYPTOGRAPHIC METHODS NOT ONLY FOR CLOSURE\
WITH THE AIM OF EITHER BREAKING THEM I E ABOLISHING THEIR\
PROTECTIVE FUNCTION OR OR TO PROVE AND QUANTIFY THEIR\
SECURITY CRYPTANALYSIS IS THUS THE COUNTERPART TO\
CRYPTOGRAPHY BOTH ARE SUBFIELDS OF CRYPTOLOGY",
"DIE KRYPTOANALYSE IN NEUEREN PUBLIKATIONEN AUCH\
KRYPTANALYSE BEZEICHNET IM URSPRUNGLICHEN SINNE DAS STUDIUM\
VON METHODEN UND TECHNIKEN UM INFORMATIONEN AUS\
VERSCHLUSSELTEN TEXTEN ZU GEWINNEN DIESE INFORMATIONEN\
KONNEN SOWOHL DER VERWENDETE SCHLUSSEL ALS AUCH DER\
ORIGINALTEXT SEIN HEUTZUTAGE BEZEICHNET DER BEGRIFF\
KRYPTOANALYSE ALLGEMEINER DIE ANALYSE VON KRYPTOGRAPHISCHEN\
VERFAHREN NICHT NUR ZUR VERSCHLUSSELUNG MIT DEM ZIEL DIESE\
ENTWEDER ZU BRECHEN D H IHRE SCHUTZFUNKTION AUFZUHEBEN BZW\
ZU UMGEHEN ODER IHRE SICHERHEIT NACHZUWEISEN UND ZU\
QUANTIFIZIEREN KRYPTOANALYSE IST DAMIT DAS GEGENSTUCK ZUR\
KRYPTOGRAPHIE BEIDE SIND TEILGEBIETE DER KRYPTOLOGIE",
"MVWZXYXEJIWGC ML BIAORR ZYZVMAKXGYRQ KPQY GPITRKRYVCQSW\
POJCBW GX XFO SPSKGXEJ CILCI RY XFO WREHW YJ KOXFYHQ KRB\
DIARRGAYCC XM YFRKML SRDYVKKXGYR DBSK CIYVIB DIVDW RRMQ\
SRDYVKKXGYR AKR ZO FMDL RRI IOC SCIB KRB DLC YVGQMLKP ROBR\
XSUKHYIW, RRI ROVK MVWZXYXEJIWGC QMBI EORCBEJVC POJCBW RY\
XFO ELKPWCMQ YJ ABCNDSEBENRMA WIRRSBC RMD SLVC DYV AVSQEVC\
GMRR XFO EGW SD OMRRIP LVCKOGXK RRIK S I YLSJSWFSRE DLCSV\
NBSROGRSZC PYLMXGYR MB SP DS NBSTO ELN USKRRSJW DLCSV\
QOGSBMRI GPITRKRYVCQSW GC XFEW RRI AYYLDIPZEPD XM\
MVWZXMQVYZLW LSRR EPO WSLJGOPBC SD MVWZXMVSEI",
"FUBSWDQDOBVLV LQ UHFHQW SXEOLFDWLRQV DOVR FUBSWDQDOBVLV\
UHIHUV LQ WKH RULJLQDO VHQVH WR WKH VWXGB RI PHWKRGV DQG\
WHFKQLTXHV WR REWDLQ LQIRUPDWLRQ IURP VHDOHG WHAWV WKLV\
LQIRUPDWLRQ FDQ EH ERWK WKH NHB XVHG DQG WKH RULJLQDO WHAW\
QRZDGDBV, WKH WHUP FUBSWDQDOBVLV PRUH JHQHUDOOB UHIHUV WR\
WKH DQDOBVLV RI FUBSWRJUDSKLF PHWKRGV QRW RQOB IRU FORVXUH\
ZLWK WKH DLP RI HLWKHU EUHDNLQJ WKHP L H DEROLVKLQJ WKHLU\
SURWHFWLYH IXQFWLRQ RU RU WR SURYH DQG TXDQWLIB WKHLU\
VHFXULWB FUBSWDQDOBVLV LV WKXV WKH FRXQWHUSDUW WR\
FUBSWRJUDSKB ERWK DUH VXEILHOGV RI FUBSWRORJB",
"RHVST TEYSJ KMHUM BBCLC GLKBM HBSJH HDAYC PPWHD UUTAP STJAI\
YMXKA OKARN NATNG CVRCH BNGJU EMXWH UERZE RLDMX MASRT LAHRJ\
KIILJ BQCTI BVFZW TKBQE OPKEQ OEBMU NUTAK ZOSLD MKXVO YELLX\
SGHTT PNROY MORRW BWZKX FFIQJ HVDZZ JGJZY IGYAT KWVIB VDBRM\
BNVFC MAXAM CALZE AYAZK HAOAA ETSGZ AAJFX HUEKZ IAKPM FWXTO\
EBUGN THMYH FCEKY VRGZA QWAXB RSMSI IWHQM HXRNR XMOEU ALYHN\
ACLHF AYDPP JBAHV MXPNF LNWQB WUGOU LGFMO BJGJB PEYVR GZAQW\
ANZCL XZSVF BISMB KUOTZ TUWUO WHFIC EBAHR JPCWG CVVEO LSSGN\
EFGCC SWHYK BJHMF ONHUE BYDRS NVFMR JRCHB NGJUB TYRUU TYVRG\
ZAXWX CSADX YIAKL INGXF FEEST UWIAJ EESFT HAHRT WZGTM CRS"
]

    
for j in range(0,5):
    
    
    numerator=0

    for i in range(65,91):
        num=list[j].count(chr(i))
        numerator+=num*(num-1)
    
    total=len(list[j])

    total-=list[j].count(chr(32))
    total-=list[j].count(chr(44))
    
    if(j!=4):
        print("3-"+str(j+1)+" "+str(numerator/(total*(total-1))))
    else:
        print("4-1" ,numerator/(total*(total-1)),sep=" ")